analytics:
  target: local
  outputs:
    local:
      type: duckdb
      path: '../data/warehouse.duckdb'
      threads: 4

    dev:
      type: duckdb
      path: '/opt/warehouse/warehouse.duckdb'
      threads: 1

    prod:
      type: duckdb
      path: '/opt/warehouse/warehouse.duckdb'
      threads: 8
