analytics:
  target: local
  outputs:
    local:
      type: duckdb
      path: '../data/dbt.duckdb'
      extensions:
        - ducklake
      attach:
        - path: "ducklake:../data/catalog.duckdb"
          alias: lakehouse
      schema: marts
      threads: 4

    dev:
      type: duckdb
      path: ':memory:'
      extensions:
        - ducklake
        - postgres
      attach:
        - path: "ducklake:postgres:dbname=ducklake_catalog host=postgres user=airflow password=airflow"
          alias: lakehouse
      schema: marts
      threads: 4

    prod:
      type: duckdb
      path: ':memory:'
      extensions:
        - ducklake
        - postgres
      attach:
        - path: "ducklake:postgres:dbname=ducklake_catalog host=postgres user=airflow password=airflow"
          alias: lakehouse
      schema: marts
      threads: 8
