receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    api_version: "1.44"
    collection_interval: 15s
    timeout: 20s
    metrics:
      container.cpu.utilization:
        enabled: true
      container.cpu.usage.total:
        enabled: false

processors:
  batch:
    timeout: 10s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp, docker_stats]
      processors: [batch]
      exporters: [prometheus, debug]
